/**
 * 构建宿主半：src/index.ts → lib/index.js（ESM bundle）。
 *
 * 设计取舍：
 * - `@deepseek-ai/*` 一律 external —— 运行时由 profile 的
 *   `~/.dsh/profiles/node_modules/@deepseek-ai/*`（junction，与 dsh 同版本）解析；
 *   尤其 schemastery 绝不能打包第二份，否则 Config schema 会是另一个类身份。
 * - `ws` 打进产物：本包以 `link:` 方式装进 profile，pnpm 不会为它建自己的
 *   node_modules，所以任何非 SDK 依赖都必须内联，否则运行时找不到。
 *   代价是 ESM 产物里出现 CJS 的 `require('events')`：esbuild 的 `__require` 垫片在
 *   `typeof require === "undefined"` 时直接抛错，所以必须在 banner 里用
 *   `createRequire(import.meta.url)` 造一个真实的 `require`。
 * - `bufferutil` / `utf-8-validate` 是 ws 的可选加速依赖，保持 external（缺失时
 *   ws 自己会优雅回退到 JS 实现）。
 */
import { build } from 'esbuild'
import { fileURLToPath } from 'node:url'
import { mkdirSync } from 'node:fs'

const root = fileURLToPath(new URL('..', import.meta.url))
mkdirSync(root + 'lib', { recursive: true })

/** ESM 里补出真实 require，供内联的 CJS 依赖（ws）使用。 */
const REQUIRE_SHIM = [
  "import { createRequire as __dsTtsCreateRequire } from 'node:module';",
  'const require = __dsTtsCreateRequire(import.meta.url);',
  '// ds-tts host half — generated by scripts/build-host.mjs; edit src/ instead.',
].join('\n')

const ENTRIES = [
  { in: 'src/index.ts', out: 'lib/index.js' },
  // 测试入口：把内部零件导出一份给 node --test 用（不对外暴露）
  { in: 'src/testing.ts', out: 'lib/testing.js' },
]

for (const entry of ENTRIES) {
  const result = await build({
    entryPoints: [root + entry.in],
    outfile: root + entry.out,
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: ['node22'],
    sourcemap: true,
    logLevel: 'warning',
    external: ['@deepseek-ai/*', 'bufferutil', 'utf-8-validate'],
    banner: { js: REQUIRE_SHIM },
  })
  if (result.errors.length > 0) process.exit(1)
  console.log(`host bundle written to ${entry.out}`)
}
